version: '3.8'

services:
  nodejs:
    build: .
    ports: 
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge