version: '3.8'

services:
  # TODO: uncomment for production
  # api:
  #   build: .
  #   ports: 
  #     - "8080:8080"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"